// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HybridSettings } from "./HybridSettings";

/**
 * Application settings
 */
export type AppSettings = { language: string, modelId: string, echoCancel: number, useVoiceIsolation: boolean, captureSystem: boolean, vadMode: string | null, vadMethod: string | null, theme: string | null, ollamaModel: string, ollamaUrl: string, diarizationEnabled: boolean, diarizationProvider: string | null, showSessionStats: boolean, hybridTranscription: HybridSettings | null, };
