// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Audio level event (for VU meters)
 */
export type AudioLevelEvent = { micLevel: number, sysLevel: number, duration: number, micMuted: boolean, sysMuted: boolean, };
