// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Audio input device information
 */
export type AudioDevice = { 
/**
 * Device ID
 */
id: string, 
/**
 * Human-readable device name
 */
name: string, 
/**
 * Whether this is the default device
 */
isDefault: boolean, 
/**
 * Number of input channels
 */
channels: number, 
/**
 * Sample rate in Hz
 */
sampleRate: number, };
