// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Chunk status
 */
export type ChunkStatus = "pending" | "transcribing" | "completed" | "error";
