// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DialogueEntry } from "./DialogueEntry";

/**
 * Audio chunk with transcription
 */
export type Chunk = { id: string, index: number, startMs: bigint, endMs: bigint, duration: bigint, transcription: string | null, micText: string | null, sysText: string | null, dialogue: Array<DialogueEntry>, isStereo: boolean, status: string, error: string | null, };
