// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranscriptWord } from "./TranscriptWord";

/**
 * Dialogue entry with speaker information
 */
export type DialogueEntry = { start: bigint, end: bigint, text: string, speaker: string, words: Array<TranscriptWord> | null, };
