// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Engine type for transcription
 */
export type EngineType = "whisper" | "gigaam" | "fluid-asr" | "speaker" | "diarization" | "vad";
