// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Hybrid transcription settings
 */
export type HybridSettings = { enabled: boolean, secondaryModelId: string, confidenceThreshold: number, contextWords: number, useLlmForMerge: boolean, mode: string, hotwords: Array<string>, };
