// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Arguments for import_audio command
 */
export type ImportAudioArgs = { path: string, language: string | null, };
