// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Model information with all fields matching frontend expectations
 */
export type ModelInfo = { 
/**
 * Model ID (e.g., "ggml-base")
 */
id: string, 
/**
 * Human-readable name
 */
name: string, 
/**
 * Model type (ggml, onnx, coreml)
 */
type: string, 
/**
 * Engine type (whisper, gigaam, fluid-asr, diarization, vad)
 */
engine: string, 
/**
 * Human-readable size (e.g., "141 MB")
 */
size: string, 
/**
 * Size in bytes
 */
sizeBytes: bigint, 
/**
 * Description
 */
description: string, 
/**
 * Supported languages
 */
languages: Array<string>, 
/**
 * Word Error Rate (optional)
 */
wer: string | null, 
/**
 * Speed multiplier (e.g., "~7x")
 */
speed: string, 
/**
 * Is this a recommended model?
 */
recommended: boolean, 
/**
 * Download URL
 */
downloadUrl: string | null, 
/**
 * Is model in archive format
 */
isArchive: boolean, 
/**
 * Model status
 */
status: string, 
/**
 * Download progress (0-100)
 */
progress: number, 
/**
 * Error message if any
 */
error: string | null, 
/**
 * Path to downloaded model
 */
path: string | null, };
