// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Model download progress event
 */
export type ModelDownloadProgressEvent = { modelId: string, progress: number, downloadedBytes: bigint, totalBytes: bigint, };
