// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Model status
 */
export type ModelStatus = "not_downloaded" | "downloading" | "downloaded" | "active" | "error";
