// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Recording result (returned when stopping recording)
 */
export type RecordingResult = { sessionId: string, durationMs: bigint, sampleCount: number, chunksCount: number, };
