// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Arguments for rename_session_speaker command
 */
export type RenameSpeakerArgs = { sessionId: string, speakerId: string, newName: string, };
