// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Arguments for search_sessions command
 */
export type SearchSessionsArgs = { query: string, };
