// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Chunk } from "./Chunk";

/**
 * Full session data
 */
export type Session = { id: string, startTime: string, endTime: string | null, status: string, chunks: Array<Chunk>, dataDir: string, totalDuration: bigint, title: string | null, tags: Array<string>, summary: string | null, language: string | null, model: string | null, sampleCount: bigint | null, };
