// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Session information (lightweight, for lists)
 */
export type SessionInfo = { id: string, startTime: string, status: string, totalDuration: bigint, chunksCount: number, title: string | null, tags: Array<string> | null, };
