// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Session speaker info (for UI)
 */
export type SessionSpeaker = { 
/**
 * Speaker ID within session (e.g., "mic", "sys", "Собеседник 1")
 */
id: string, 
/**
 * Display name (can be renamed by user)
 */
displayName: string, 
/**
 * Whether this is the microphone user
 */
isMic: boolean, 
/**
 * Whether speaker was recognized via voiceprint
 */
isRecognized: boolean, 
/**
 * Associated voiceprint ID (if recognized)
 */
voiceprintId: string | null, 
/**
 * Number of dialogue entries for this speaker
 */
entryCount: number, 
/**
 * Total duration in milliseconds
 */
totalDurationMs: bigint, };
