// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Session } from "./Session";

/**
 * Session stopped event payload
 */
export type SessionStoppedEvent = { sessionId: string, session: Session | null, };
