// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Speaker segment from diarization
 */
export type SpeakerSegment = { 
/**
 * Start time in seconds
 */
start: number, 
/**
 * End time in seconds
 */
end: number, 
/**
 * Speaker ID (0, 1, 2...)
 */
speaker: number, };
