// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Arguments for start_recording command
 */
export type StartRecordingArgs = { deviceId: string | null, captureSystem: boolean, language: string | null, };
