// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single word with timing information
 */
export type TranscriptWord = { 
/**
 * Start time in milliseconds
 */
start: bigint, 
/**
 * End time in milliseconds  
 */
end: bigint, 
/**
 * The word text
 */
text: string, 
/**
 * Confidence score (0.0 - 1.0)
 */
confidence: number, };
