// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranscriptWord } from "./TranscriptWord";

/**
 * A segment of transcribed text with timing information
 */
export type TranscriptSegment = { 
/**
 * Start time in milliseconds
 */
start: bigint, 
/**
 * End time in milliseconds
 */
end: bigint, 
/**
 * Transcribed text
 */
text: string, 
/**
 * Speaker identifier (e.g., "Speaker 0")
 */
speaker: string | null, 
/**
 * Word-level timestamps
 */
words: Array<TranscriptWord>, 
/**
 * Confidence score (0.0 - 1.0)
 */
confidence: number, };
