// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TranscriptSegment } from "./TranscriptSegment";

/**
 * Transcription result
 */
export type TranscriptionResult = { 
/**
 * Full transcribed text
 */
text: string, 
/**
 * Segments with timestamps
 */
segments: Array<TranscriptSegment>, 
/**
 * Detected language (ISO 639-1 code)
 */
language: string | null, 
/**
 * Processing time in milliseconds
 */
processingTimeMs: bigint, 
/**
 * Real-time factor (audio_duration / processing_time)
 */
rtf: number, };
