// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * VoicePrint for speaker recognition
 */
export type VoicePrint = { id: string, name: string, createdAt: string, updatedAt: string, 
/**
 * Number of samples used to create this voiceprint
 */
sampleCount: number, };
