// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Waveform data for visualization
 */
export type WaveformData = { peaks: Array<Array<number>>, rms: Array<Array<number>>, rmsAbsolute: Array<Array<number>>, sampleDuration: number, duration: number, sampleCount: bigint, channelCount: number, };
